### ISSUE TITLE
Crash on Android P

### ISSUE THREAD

**Issue by hemanshuasolia** [karthikraj-duraisamy/ShapesImage#2]
We get following stacktrace on Android P: 
    Process: com.flowboat.dsco, PID: 21605
    java.lang.IllegalArgumentException: Invalid Layer Save Flag - only ALL_SAVE_FLAGS is allowed
        at android.graphics.Canvas.checkValidSaveFlags(Canvas.java:378)
        at android.graphics.Canvas.saveLayer(Canvas.java:455)
        at net.karthikraj.shapesimage.ShapesImage.onDraw(ShapesImage.java:590)
        at android.view.View.draw(View.java:20207)
        at android.view.View.updateDisplayListIfDirty(View.java:19082)
        at android.view.View.draw(View.java:19935)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at android.view.View.updateDisplayListIfDirty(View.java:19073)
        at android.view.View.draw(View.java:19935)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at android.view.View.draw(View.java:20210)
        at android.view.View.updateDisplayListIfDirty(View.java:19082)
        at android.view.View.draw(View.java:19935)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at android.support.v7.widget.RecyclerView.drawChild(RecyclerView.java:4820)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at android.view.View.draw(View.java:20210)
        at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:4219)
        at android.view.View.updateDisplayListIfDirty(View.java:19082)
        at android.view.View.draw(View.java:19935)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at android.view.View.draw(View.java:20210)
        at android.view.View.updateDisplayListIfDirty(View.java:19082)
        at android.view.View.draw(View.java:19935)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at android.view.View.updateDisplayListIfDirty(View.java:19073)
        at android.view.View.draw(View.java:19935)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at android.view.View.updateDisplayListIfDirty(View.java:19073)
        at android.view.View.draw(View.java:19935)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at android.view.View.updateDisplayListIfDirty(View.java:19073)
        at android.view.View.draw(View.java:19935)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at android.view.View.updateDisplayListIfDirty(View.java:19073)
        at android.view.View.draw(View.java:19935)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at android.view.View.draw(View.java:20210)
        at com.android.internal.policy.DecorView.draw(DecorView.java:780)
        at android.view.View.updateDisplayListIfDirty(View.java:19082)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:686)

Similar issues reported in other projects: ( https://github.com/airbnb/lottie-android/issues/747)

**Comment by mojirzg** [comment]
I have the same problem here.

Brand: Asus
Model: ZenFone 2 Laser (ZE550KLA)
Operating System Version: 9
Orientation: Portrait
Rooted: Yes

Stack trace :

Fatal Exception: java.lang.IllegalArgumentException: Invalid Layer Save Flag - only ALL_SAVE_FLAGS is allowed
       at android.graphics.Canvas.checkValidSaveFlags(Canvas.java:378)
       at android.graphics.Canvas.saveLayer(Canvas.java:455)
       at net.karthikraj.shapesimage.ShapesImage.onDraw(ShapesImage.java:590)
       at android.view.View.draw(View.java:20227)
       at android.view.View.updateDisplayListIfDirty(View.java:19102)
       at android.view.View.draw(View.java:19955)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
       at android.support.constraint.ConstraintLayout.dispatchDraw(ConstraintLayout.java:2023)
       at android.view.View.updateDisplayListIfDirty(View.java:19093)
       at android.view.View.draw(View.java:19955)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
       at android.support.v7.widget.RecyclerView.drawChild(RecyclerView.java:4820)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
       at android.view.View.draw(View.java:20230)
       at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:4219)
       at android.view.View.updateDisplayListIfDirty(View.java:19102)
       at android.view.View.draw(View.java:19955)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
       at android.support.constraint.ConstraintLayout.dispatchDraw(ConstraintLayout.java:2023)
       at android.view.View.updateDisplayListIfDirty(View.java:19093)
       at android.view.View.draw(View.java:19955)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
       at android.view.View.updateDisplayListIfDirty(View.java:19093)
       at android.view.View.draw(View.java:19955)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
       at android.support.constraint.ConstraintLayout.dispatchDraw(ConstraintLayout.java:2023)
       at android.view.View.updateDisplayListIfDirty(View.java:19093)
       at android.view.View.draw(View.java:19955)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
       at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1426)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
       at android.view.View.draw(View.java:20230)
       at android.view.View.updateDisplayListIfDirty(View.java:19102)
       at android.view.View.draw(View.java:19955)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
       at android.view.View.updateDisplayListIfDirty(View.java:19093)
       at android.view.View.draw(View.java:19955)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
       at android.view.View.updateDisplayListIfDirty(View.java:19093)
       at android.view.View.draw(View.java:19955)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
       at android.view.View.updateDisplayListIfDirty(View.java:19093)
       at android.view.View.draw(View.java:19955)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
       at android.view.View.updateDisplayListIfDirty(View.java:19093)
       at android.view.View.draw(View.java:19955)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
       at android.view.View.draw(View.java:20230)
       at com.android.internal.policy.DecorView.draw(DecorView.java:780)
       at android.view.View.updateDisplayListIfDirty(View.java:19102)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:698)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:704)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:813)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:3325)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3129)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2498)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1474)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7377)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
       at android.view.Choreographer.doCallbacks(Choreographer.java:761)
       at android.view.Choreographer.doFrame(Choreographer.java:696)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6723)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
